---
- name: Setup NGINX webserver
  hosts: webservers
  remote_user: admin
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www

  tasks:
  - name: Make sure all repos are updated
    apt:
      update_cache: yes
  
  - name: Install NGINX
    apt:
      name: nginx
      state: latest
  
  - name: Start NGINX
    service:
      name: nginx
      state: restarted
      enabled: yes

  - name: Create sites-available directory
    file:
      path: /etc/nginx/sites-available
      state: directory

  - name: Create sites-enabled directory
    file:
      path: /etc/nginx/sites-enabled
      state: directory
  
  # - name: Copy files to document root
  #   copy:
  #     src: "{{ site_dir }}"
  #     dest: "{{ document_root }}"
  
  - name: Apply NGINX template
    template:
      src: "{{ config_file_name }}"
      dest: /etc/nginx/sites-available/{{ site_name }}
  
  - name: Enable website
    file:
      src: /etc/nginx/sites-available/{{ site_name }}
      dest: /etc/nginx/sites-enabled/{{ site_name }}
      state: link
    notify: Restart NGINX

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted